name: dotmeme
description: "Meme search engine"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  settings_ui: ^1.0.0
  photo_view: ^0.12.0

  # Logic and stuff
  ## DB
  moor: ^4.4.1

  ## State management
  flutter_bloc: ^7.1.0

  memoize:
    # TODO: Change this tu pub when it gets merged
    git:
      url: "https://github.com/KanarekApp/memoize_dart"
      ref: "_multiple_results_stash"
  async: ">=2.0.0 <3.0.0"
  equatable: ^2.0.3
  logger: ^1.0.0

  ## DI
  get_it: ^7.2.0

  # Platform tools
  ## Dart native
  path: ^1.8.0
  mime: ^1.0.0
  image: ^3.0.2
  image_size_getter: ^1.0.0
  watcher: ^1.0.0
  ## Plugins
  path_provider: ^2.0.2
  share_plus: ^2.1.4
  sqlite3_flutter_libs: ^0.5.0

  flutter_tesseract_ocr:
    git:
      url: "https://github.com/khjde1207/tesseract_ocr"
      ref: "master"

  photo_manager: ^1.3.1
  permission_handler: ^8.1.4+2
  flutter_foreground_task: ^2.2.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^5.0.14

  # Generators
  moor_generator: ^4.4.1
  build_runner: ^2.1.1

  # Style
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tessdata/
