name: dotmeme
description: "Meme search engine"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI

  # Logic and stuff
  ## DB
  moor: ^4.3.2

  ## State management
  flutter_bloc: ^7.0.1

  equatable: ^2.0.3

  # Platform tools
  path_provider: ^2.0.2
  path: ^1.8.0
  sqlite3_flutter_libs: ^0.5.0

  photo_manager: ^1.2.4
  permission_handler: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^4.3.2
  build_runner: ^2.0.5

flutter:
  uses-material-design: true
