# Run all main Flutter style and test checks
name: Main Flutter checks

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  flutter_version: "2.2.3"
  flutter_channel: "stable"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Flutter
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ env.flutter_channel }}
    - uses: subosito/flutter-action@v1.5.3
      with:
        flutter-version: ${{ env.flutter_version }}
        channel: ${{ env.flutter_channel }}
    - run: flutter pub get
    - run: flutter format --set-exit-if-changed lib test
    - run: flutter analyze lib test
    - name: Setup test env
      run: |
        ./scripts/setup-test-media.sh
        ./scripts/setup-ocr.sh
    - name: Run tests
      run: flutter test --no-pub --coverage
