# Run all main Flutter style and test checks
name: Main Flutter checks

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.0
    - run: flutter pub get
    - run: flutter format --set-exit-if-changed lib test
    - run: flutter analyze lib test
    - name: Run tests
      run: flutter test --no-pub --coverage
    # TODO: Delete later
    - run: sudo apt install tree
    - run: tree
